baseURL: "http://zhiva.be/"
languageCode: "bg-bg"
title: "Жива Мрежа"
theme: "xmin"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Жива Мрежа
      url: ""
      weight: 1

    - name: Добави услуга
      url: "/добави"
      weight: 2

    - name: Цели
      url: "/цели"
      weight: 3

    - name: Как работи
      url: "/как-работи"
      weight: 4

params:
  description: "Жива Мрежа Описание."
  footer: Жива Мрежа | [Пиши ни](mailto:da@zhiva.be) | [Отворен код](https://github.com/zhiva-mrezha) 

