baseURL: "http://zhiva.be/"
languageCode: "bg-bg"
title: "Жива Мрежа"
theme: "xmin"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Жива Мрежа
      url: ""
      weight: 1

    - name: Влез
      url: "https://az.zhiva.be/auth/realms/zhiva-mrezha/account"
      weight: 2

    - name: Добави услуга
      url: "/добави"
      weight: 3

    - name: Цели
      url: "/цели"
      weight: 4

    - name: Как работи
      url: "/как-работи"
      weight: 5

params:
  description: "Жива Мрежа Описание."
  footer: Жива Мрежа | [Пиши ни](/пиши-ни) | [Отворен код](https://github.com/zhiva-mrezha) 
  services: 
    - name: Облак
      url: https://oblak.otselo.eu
      description: "общностен календар, раздумка" 
    - name: Аз
      url: https://az.zhiva.be/auth/realms/zhiva-mrezha/account
      description: "единно влизане като потребител за всички услуги от Жива Мрежа" 
    - name: Седмичник
      url: https://7.zhiva.be
      description: "седмично е-писмо за случващото се в общността"
